### ISSUE TITLE
WebDav sync throws error starting with SuperProductitivy 9

### ISSUE THREAD

**Issue by hkockerbeck** [johannesjo/super-productivity#3269]
### Your Environment

- Version used: Snap 9.0.3, also observed on 9.0.1
- Operating System and version: Ubuntu 22.04 LTS
- Desktop Environment: Gnome 42.9
- Browser Name and version: N/A

### Expected Behavior

I expect SuperProductivity to successfully sync my data on startup, as it (to my knowledge) happened up to version 8.x.

### Current Behavior

When I start SuperProductivity, it shows an error to check the console (German language version). The error in the console is

```
Error: TypeError: (intermediate value) is not a function
    at e.<anonymous> (web-dav-sync.service.ts:58:13)
    at Generator.throw (<anonymous>)
    at i (chunk-3L47AOO2.js:1:1508)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15484:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15473:25)
```

### Steps to Reproduce (for bugs)

1. Have SuperProductivity 9.0.x (seen at 9.0.1 as well as on 9.0.3) sync with WebDav

### Can you reproduce this reliably?

Since the upgrade to 9.0.x, it happens at every start. I don't remember ever seeing the problem with SuperProductivity 8 or older.

### Console Output

```
Error: TypeError: (intermediate value) is not a function
    at e.<anonymous> (web-dav-sync.service.ts:58:13)
    at Generator.throw (<anonymous>)
    at i (chunk-3L47AOO2.js:1:1508)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15484:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15473:25)
```

### Error Log (Desktop only)

The log only contains entries from about a week ago, so probably not relevant here.

**Comment by marcogeue** [comment]
hey there
I have the same issue. I did the last normal working sync via Webdav (with my Nextcloud) on 19th July at 6∶42 PM CEST (UTC+2).
When I tried to sync yesterday with my Android-App I got the message that syncing doesn't work and today as well on my Linux App it doesn't work and I get the same console output.

I tried it now on the test-app in my browser and again I get the same mistake. The target folder exists in my Nextcloud and also the synced JSON-File lies there. In the Test App I get a large js-object as output when the error message appears:

![grafik](https://github.com/user-attachments/assets/387070bb-a286-4b06-ac26-cf0e87225411)

**Comment by hkockerbeck** [comment]
> Does manually creating the target folder you configured in your sync settings somehow fix the issue?

Manually creating the target folder doesn't seem to make any difference, unfortunately. There's no file in the target folder, and the error in the console still is "Error: TypeError: (intermediate value) is not a function
    at e.<anonymous> (web-dav-sync.service.ts:58:13" and so on.

**Comment by johannesjo** [comment]
While I was probably not able to fix this issue, since I was unable to reproduce it, I hope that I did improve error handling. I will make a patch release later today. It would be great if you can try with that one again and report back with the console logs!

**Comment by hkockerbeck** [comment]
> While I was probably not able to fix this issue, since I was unable to reproduce it, I hope that I did improve error handling. I will make a patch release later today. It would be great if you can try with that one again and report back with the console logs!

Thank you :) Version 9.0.4 gives me the following in the console
```
TypeError: (intermediate value) is not a function
    at e.<anonymous> (web-dav-api.service.ts:161:68)
    at Generator.next (<anonymous>)
    at k (chunk-OM4HSKZI.js:1:1464)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)
```

```
__error during sync__  sync-provider.service.ts:141 
```

```
Error: (intermediate value) is not a function
    at e.<anonymous> (web-dav-sync.service.ts:60:15)
    at Generator.throw (<anonymous>)
    at i (chunk-OM4HSKZI.js:1:1508)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)
```

**Comment by johannesjo** [comment]
I was finally able to fix this (hopefully). New release is under way.

**Comment by steadfasterX** [comment]
> I was finally able to fix this (hopefully). New release is on its way. Sorry for the inconvenience!

fixed for me now! thx :)
