### ISSUE TITLE
Error: Remote archive rev does not match the one in remote main file

### ISSUE THREAD

**Issue by Raindrac** [johannesjo/super-productivity#3284]
### Your Environment

- Version used: 9.0.4 (Linux .appimage) and 9.0.4 (Android .apk)
- Operating System and version: Linux and Android 11
- Desktop Environment: Gnome

### Expected Behavior

Data is successfully pulled and synchronized from remote.

### Current Behavior

Once data from the remote is pulled from the remote on Linux when a sync is triggered, it outputs the following error:
`Error: Remote archive rev does not match the one in remote main file`

Android says "Data successful synced" when a sync is triggered and isn't reporting any issues, the issue occurs both with and without end-to-end encryption enabled, and the newest revision is on Android and being pulled by Linux.

### Steps to Reproduce (for bugs)

1. Click trigger sync manually
2. Pick keep remote

### Can you reproduce this reliably?

I don't know how to reproduce the archive rev becoming out of sync, unfortunately. I can reliably trigger the bug now that it's out of sync, but I couldn't tell ya how this happened in the first place. 

### Console Output

```
{rev: '1721680208666', localRev: null}localRev: nullrev: "1721680208666"[[Prototype]]: Object
persistence.service.ts:317 LOAD COMPLETE false
sync-provider.service.ts:930 LocalFile ↓ downloading main file
sync-provider.service.ts:864 decrypt: 1.114013671875 ms
check-for-update.util.ts:69 {local: 1721669275414, lastSync: 0, remote: 1721680198346}lastSync: 0local: 1721669275414remote: 1721680198346[[Prototype]]: Object
check-for-update.util.ts:81 {lastSync: 0, local: 1721669275.414, remote: 1721680198.346}lastSync: 0local: 1721669275.414remote: 1721680198.346[[Prototype]]: Object 1721680263.559
check-for-update.util.ts:54 DATA DIVERGED: local < remote
sync-provider.service.ts:930 LocalFile ^--------^-------^
sync-provider.service.ts:930 LocalFile ⇎ X Diverged Data
sync-provider.service.ts:930 LocalFile Dialog => ↓ Update Local
sync-provider.service.ts:930 LocalFile Archive force update chosen. Downloading...
sync-provider.service.ts:930 LocalFile ↓ downloading archive file
sync-provider.service.ts:864 decrypt: 2.36083984375 ms
sync-provider.service.ts:659 {remoteArchiveRev: '1721669259530', remoteMainFileData.archiveRev: '1721669060000'}remoteArchiveRev: "1721669259530"remoteMainFileData.archiveRev: "1721669060000"[[Prototype]]: Object
sync-provider.service.ts:141 __error during sync__
sync-provider.service.ts:142 Error: Remote archive rev does not match the one in remote main file
    at e.<anonymous> (sync-provider.service.ts:664:13)
    at Generator.next (<anonymous>)
    at k (chunk-OM4HSKZI.js:1:1464)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)

```

**Comment by Harmonia2Side** [comment]
Sadly having the same problem here. Even tried to overwrite the sync file in linux because it refused to open the file coming from android. After overwriting, syncing the files back to android generates the same error on android as well. They work individually but refuse to sync with each other.

I'm using snap in linux and F-Droid version on Android, syncing with LocalFile. Android is 9.0.5, snap is still on 9.0.4 (for some reason). Tried 9.0.5 on Linux using the .deb package, result was the same.

**Comment by johannesjo** [comment]
Thank you very much for reporting I'll work on it this Friday. Sorry for the inconvenience!

**Comment by C-M-Gonzalez** [comment]
I'll also note, that I get the same error as @Harmonia2Side and @Raindrac. 

My situation is only slightly different as the sync occurs through **_pCloud_** online storage and between a Windows 10 < -- > Linux box (Manjaro latest + appImage version). Is this a Linux issue? 

Originally, I was using the experimental encryption method to store the data on pCloud, however after the first error I removed the syncs and the encryption option and was still about to reproduce the same error. So encryption doesn't seem to be at fault there. 

The Windows versions is installed through the Microsoft store. AppImg version is the latest 9.0.5. I can provide more logs if necessary from my end when I get home from work tonight for the Linux machine. 

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎1/‎03/‎2022
OS build	19045.4651
Experience	Windows Feature Experience Pack 1000.19060.1000.0

Thank you for this application, it's wonderful. I wish I could help beyond just being a peon.

**Comment by UnconsciousBlaringHuman** [comment]
I've also experienced this error when adding a third device.
Prior to SP9 I had a 3-way localfile sync between a Win10 desktop, an Android phone, and an Android tablet. Currently, however, I'm only able to use a 2-way sync (currently set to desktop and phone), thankfully working perfectly since the recent 9.0.5 update.

**Comment by johannesjo** [comment]
I just pushed some changes that should handle that case a little more gracefully. If someone could check that on their machine that would be great (either by building yourself or using the snap edge channel)!! 

When it comes to preventing this in the first place I am not sure, since I am unable to reproduce this myself. The main factor here are the revs. The mainfile saves the value it gets when uploading the archive file and after downloading the mainfile on another machine it checks if the remote archive rev it saved maches the one of the actual file. @Raindrac value of 1721669060000 looks a bit fishy, since it appears to be a timestamp, but without milliseconds and seconds. Not sure if that is a factor.

**Comment by Raindrac** [comment]
I booted up the edge version of the snap in a virtual machine and synced, but unfortunately I'm getting the same error with revs not matching. If it helps, I might be able to email over my archive and main files with information edited out

```
{rev: '1722006106287', localRev: null}localRev: nullrev: "1722006106287"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ ()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
persistence.service.ts:317 LOAD COMPLETE false
sync-provider.service.ts:944 LocalFile ↓ downloading main file
sync-provider.service.ts:877 decrypt: 1.837158203125 ms
check-for-update.util.ts:69 {local: 1722006036046, lastSync: 0, remote: 1722006093717}lastSync: 0local: 1722006036046remote: 1722006093717[[Prototype]]: Objectconstructor: ƒ Object()assign: ƒ assign()create: ƒ create()defineProperties: ƒ defineProperties()defineProperty: ƒ defineProperty()entries: ƒ entries()freeze: ƒ freeze()fromEntries: ƒ fromEntries()getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()getOwnPropertyNames: ƒ getOwnPropertyNames()getOwnPropertySymbols: ƒ getOwnPropertySymbols()getPrototypeOf: ƒ getPrototypeOf()groupBy: ƒ groupBy()hasOwn: ƒ hasOwn()is: ƒ is()isExtensible: ƒ isExtensible()isFrozen: ƒ isFrozen()isSealed: ƒ isSealed()keys: ƒ keys()length: 1name: "Object"preventExtensions: ƒ preventExtensions()prototype: {__defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, __lookupSetter__: ƒ, …}seal: ƒ seal()setPrototypeOf: ƒ setPrototypeOf()values: ƒ values()arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ ()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
check-for-update.util.ts:81 {lastSync: 0, local: 1722006036.046, remote: 1722006093.717} 1722006289.824
check-for-update.util.ts:54 DATA DIVERGED: local < remote
sync-provider.service.ts:944 LocalFile ^--------^-------^
sync-provider.service.ts:944 LocalFile ⇎ X Diverged Data
sync-provider.service.ts:944 LocalFile Dialog => ↓ Update Local
sync-provider.service.ts:944 LocalFile Archive force update chosen. Downloading...
sync-provider.service.ts:944 LocalFile ↓ downloading archive file
sync-provider.service.ts:877 decrypt: 2.31591796875 ms
sync-provider.service.ts:672 {remoteArchiveRev: '1722005970829', remoteMainFileData.archiveRev: '1721974983000'}remoteArchiveRev: "1722005970829"remoteMainFileData.archiveRev: "1721974983000"[[Prototype]]: Object
sync-provider.service.ts:146 __error during sync__
sync-provider.service.ts:147 Error: Remote archive rev does not match the one in remote main file
    at e.<anonymous> (sync-provider.service.ts:677:13)
    at Generator.next (<anonymous>)
    at o (main-NMVQJZHY.js:1:1522)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)
```

Here's the error log from that attempt

**Comment by johannesjo** [comment]
I am sorry @Raindrac !! It seems like the upload of the snap failed (recently, they are having network issues from time to time), so I had to do it manually. The new build should be online only now.

**Comment by Raindrac** [comment]
Ah, alright! I tried again, and I'm getting a different result now:

![image](https://github.com/user-attachments/assets/1b137549-cdec-4825-8f19-b192dccf5582)

I made sure to run the sync a couple times from my Android device after making some changes and it doesn't seem to make a difference, as the snap still claims that it's an incomplete sync. Overwriting remote with local would wipe the database.

**Comment by johannesjo** [comment]
Thank you very much for checking again @Raindrac ! I think was able to fix this. Would be great if you could check once more with the edge release!

**Comment by Raindrac** [comment]
> Thank you very much for checking again @Raindrac ! I think was able to fix this. Would be great if you could check once more with the edge release!

![image](https://github.com/user-attachments/assets/99af5039-91e6-43fb-8c6d-6668674d1797)

Here we go! Still not working, unfortunately. The revs are showing now though. Looks like one is hashed, while the other is a timestamp.

**Comment by johannesjo** [comment]
Thank you very much @Raindrac ! This is likely because the mobile version is still the older version. Otherwise this looks correct (the real rev is dynamically calculated and a string rather than a timestamp). I'll provide a fix release soon. Please let me know, if it works!
